### PR TITLE
Add jsonrpc dependency info

### PR DESCRIPTION
**Pull request by tninja**
Based on
1. https://github.com/copilot-emacs/copilot.el/issues/232
2. https://github.com/copilot-emacs/copilot.el/issues/244

### CODE REVIEW

**Comment by tninja** [comment]
if there is a way to let copilot.el automatically install the dependency, it is much better than this.

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
What package manager are you using? The built-in package manager --- `package.el` will handle it for you. 🤔

**Comment by tninja** [comment]
> What package manager are you using? The built-in package manager --- `package.el` will handle it for you. 🤔

Yes. Probably should replace ELPA to package manager.

**Comment by tninja** [comment]
Move the description to installation part beside the editorconfig package dependency.

**Pull request merged**
