### PR TITLE
Bump up to copilot.vim 1.14

### PR DESCRIPTION
**Pull request by dannywillems**
Updating dist directory. I am not sure it is the only changes to perform. I'm testing on my machine with the branch [dw/main](https://github.com/dannywillems/copilot.el/tree/dw/main).

Something like:
```
git clone https://github.com/github/copilot.vim/ /tmp/copilot.vim
cd /tmp/copilot.vim
git checkout v1.14.0
git clone https://github.com/github/copilot.vim/ /tmp/copilot.el
cd /tmp/copilot.el
rm -rf dist
cp -r /tmp/copilot.vim/dist/ /tmp/copilot.el/dist
```

### CODE REVIEW

**Comment by zerolfx** [comment]
@dannywillems Thanks for testing! For convenience and integrity, we'll use CI to update the dist folder. We disabled automatic CI updates due to potential breaking changes.
@emil-vdw You can manually trigger the GitHub workflow to update the dist folder and close the PR as well as related issues then.

**Comment by emil-vdw** [comment]
@zerolfx I ran the workflow but it resulted in an authentication error. Maybe related to the repo move or the token just expired? Anyway I don't have access to be able to fix it myself. If you wouldn't mind checking the `secrets.GITHUB_TOKEN` is correct.

**Comment by zerolfx** [comment]
@emil-vdw Fixed. Please also help on updating the CI to remove old files from the dist directory.

**Comment by emil-vdw** [comment]
Update handled by workflow. #242 opened to remove dist files that have been removed upstream.

**Pull request closed without merging**
