### PR TITLE
Adding link to copilot-chat.el project in README

### PR DESCRIPTION
**Pull request by tninja**
Currently copilot.el don't have chat capability. But github plugin for IntelliJ and VSCode have.

I happen to find the copilot-chat.el project on github. It might be less known than copilot.el. I tried that, it works well. I think it worth to have a link in the README, it is complimentary to copilot.el, and could be useful to people.

### CODE REVIEW

**Comment by tninja** [comment]
Although this package named "Unofficial", it seems that it is in practical the official github copilot integration in emacs. Personally I think it is very important to emacs community. 

Unfortunately i didn't see the maintainer looking after issues and PRs. @emil-vdw, @jcs090218, @rakotomandimby, Can you help look into those opened PRs and issues? Thanks in advance.

**Comment by tninja** [comment]
Also @zerolfx if you have time. Thanks.

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
I'd like to do more with this plugin, but I don't have full push or merge permissions. 😅 

Anyway, thank you for the changes!

**Comment by tninja** [comment]
> I'd like to do more with this plugin, but I don't have full push or merge permissions. 😅
> 
> Anyway, thank you for the changes!

Thanks for the reply. This package is used in my daily work and I do wish it have a good future.

**Pull request merged**
