### PR TITLE
fix: Better compatible with jsonrpc

### PR DESCRIPTION
**Pull request by jcs090218**
For #258.

### CODE REVIEW

**Comment by emil-vdw** [comment]
Have you tested on old and new version of `jsonrpc`?

**Comment by jcs090218** [comment]
Yes, it both works for me. :)

**Comment by emil-vdw** [comment]
Don't you think that it would be better for this "old" `jsonrpc` version to be hardcoded? It's not really like it can change and we should only use the old parameter when it is older than that specific version not when it is older than the version we currently rely upon. I.e. at some point we may update the version of `jsonrpc` we depend on but the logic would break.

**Comment by emil-vdw** [comment]
Nevermind, I was confused there for a second. LGTM. :+1:

**Comment by jkl1337** [comment]
This is completely broken. Compilation breaks due to Package-Requires not at sufficient version (28.1). Furthermore, package-get-descriptor is only going to work if the descriptor is loaded first, and just requiring 'jsonrpc doesn't do that. As it is this breaks emacs startup.

**Pull request merged**
